# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzswN7Szgo1GFgR4MJM4x1TKh4k_nFx0
"""

print("hey")
# for(i=0;i<10;i++)

for i in range(1,6,2):
  print("hey",i)

for i  in range(6,1,-1):
  print("hey",i)

for i in "hey":
  print(i)

x="hey"
for index in range (0,3):
 print(x[index])

for i in range(1,31):
 if(i%5==0):
  print(i)

10%3

for i in range(99,1,-1):
  if(i%2==0 and i%3==0):
    print(i)

# 1 to 5
# 1+2+3+5=>15
total=0
for i in range(1,6):
  total=total+i
  print("total value:",total)

total=0
for i in "hey123":
 total=total+1
 print("total value:",total)

'''
while (true):
  statement
'''
i=0
while (i<10):
  print(i)
  i+=1

for i in range(1,5):
  for j in range(1,5):
    print("*",end=" ")

  print("")

print("hello tushar",end=" ")
print("hello aman")

for i in range(1,5):
  for j in range(1,6):
    print(j,end=" ")

  print(" ")

for i in range(1,6):
  for j in range(5,0,-2):
    print(j,end=" ")

  print(" ")

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")

  print(" ")

for i in range(5,1,):
  for j in range(5,i-1):
    print("*",end=" ")

  print(" ")